APP_NAME = paloma

BIN_DIR = bin
SRC_DIR = cmd/app

MAIN_FILE = $(SRC_DIR)/main.go
EXEC_FILE = $(BIN_DIR)/$(APP_NAME)


# THESE ARE THE FILES GENERATED BY TEMPLATES THAT NEED TO BE REMOVED BEFORE REGENERATING
TEMP_FILES += $(wildcard **/*_templ.go)
TEMP_FILES += $(wildcard **/*_templ.txt)

.PHONY: run build

build:
	@echo "Building $(APP_NAME)"
	@go build -o $(EXEC_FILE) $(MAIN_FILE)

run:
	@echo "Running $(APP_NAME)"
	@./$(EXEC_FILE)

again: build
	@echo "Running $(APP_NAME)"
	@./$(EXEC_FILE)

include ./build/migrations.mk
