# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy to Production Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to prod server
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PROD_TOKEN }}
